### ISSUE TITLE
Create a database with required specifications

### ISSUE THREAD

**Issue by akshit-g** [upes-open/OSoC-Resource-Sharing-App#5]
Design the database schema to store user information, educational resources, and other relevant data. Determine the relationships between different entities and define their attributes. Choose a suitable database management system like PostgreSQL.

**Comment by rohin079** [comment]
I would like to work on this issue under OSoc'23

**Comment by akshit-g** [comment]
Assigned!

**Comment by rohin079** [comment]
Created the required database on PostgreSQL on render according to the schema made under this issue. Here is the screenshot for the required table structure: 

![tablessss](https://github.com/upes-open/OSoC-Resource-Sharing-App/assets/38971621/0b87a650-2789-42f0-a0be-1bd48dc24306)

I can share the render login credentials to further work upon the database.

For now, since none of the files are changed, i can't really commit anything to raise a PR. Consider this comment a PR for this issue

**Comment by akshit-g** [comment]
Okay, closing this issue.
Completed by @rohin079
